이메일 비밀번호 찾기 기능 구현
witherview/witherview_frontend pull request #119
Opened 2021-07-11 14:35 UTC by Sung-jin

> resolve #118 

## Detail & Solution
* 패스워드 변경 이메일 요청 기능과 이메일에 있는 링크를 접근하여 패스워드 변경하도록 기능구현했습니다.

## What I did
* 패스워드 변경 요청 api 기능 연결하여, 입력한 이메일로 패스워드 변경 요청 메일이 전송되는 기능을 구현하였습니다.
* 이메일로 전달받은 링크를 접속하면, 해당 url 에 있는 토큰값을 이용하여 패스워드 변경되도록 기능 구현했습니다.
* 패스워드 변경 화면을 접근할 때, 토큰이 없으면 메인 페이지로 튕기도록 구현했습니다.

## What I need to do

2021-07-11 14:42 UTC, Sung-jin commented on src/pages/PasswordPage/PasswordPage.stories.js
> +export const login = () => <PasswordPage />;
해당 스토리북을 접근하면 에러가 발생하는데,

```jsx
propTypes = {
  history: ReactRouterPropTypes.history.isRequired,
  location: ReactRouterPropTypes.location,
};
```

위 형태로 reactRouter 값을 자동으로 넘겨주게 해놨는데, 스토리북에서는 해당 값이 전달되지 않는 것 같습니다. 그리고 이메일 요청하는 서버 기능과 결합도가 높아서.. 따로 스토리북 형태로 두기가 좀 애매한 것 같습니다.

url 에 있는 param 을 이용해야 하는데.. 스토리북에서도 할 수 있는지 잘 모르겠습니다.

여기 컴포넌트는 스토리북을 제외할까요? 방법을 찾아볼까요? 좋은 방법이 있다면 의견 부탁드립니다.

2021-07-11 14:42 UTC, Sung-jin commented on src/pages/PasswordPage/PasswordPage.js
> +          {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events,jsx-a11y/no-static-element-interactions */}
예전에 @wooooooood 님이 div 등에 onClick 이벤트를 붙이면 lint 경고가 발생해서, 해결했었던거 같은데 혹시 어떤 이슈였는지 알 수 있을까요?

린트 내용은 [링크](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/click-events-have-key-events.md) 내용입니다.

2021-07-12 04:58 UTC, wooooooood commented on src/pages/PasswordPage/PasswordPage.js
> +          {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events,jsx-a11y/no-static-element-interactions */}
넵 저도 #90 에서 새로운 스타일 컨벤션 적용하면서 같은 오류가 발생해서 결국 해당 파일에 대해서 린트 disable하는 방향으로 처리했었습니다 ㅠ
저같은 경우는 div로 작성된 드롭다운에 onClick 이벤트가 있어서 발생했었어요! 
styled-comp 쓸때는 안잡히던데 린트가 시멘틱 태그를 중시하나 싶네요,,

2021-07-14 16:07 UTC, dididy commented on src/pages/PasswordPage/PasswordPage.stories.js
> +export const login = () => <PasswordPage />;
MemoryRouter를 사용하는 방법이 있을 것 같습니다. 저도 같이 고민해보겠습니다.

2021-07-24 14:02 UTC, dididy requested changes
생각해보아야 할 부분 코멘트 남겼습니다!

2021-07-24 14:02 UTC, voidmatcha commented on src/pages/PasswordPage/PasswordPage.js
> +      }
```suggestion
 .box-container {
        display: contents;
        > div:not(:nth-last-child(1)) {
          padding-top: 2vh;
          ${({ theme }) => theme.input}
        }
      }

      .button-container {
        display: flex;
        justify-content: center;
        padding-top: ${({ mode }) => `${mode === 'find' ? '8vh' : '5.5vh'}`};
        ${({ theme }) => theme.button}
      }
```

2021-07-24 14:02 UTC, voidmatcha commented on src/pages/PasswordPage/PasswordPage.js
> +        }
```suggestion
        if (result.status !== 200) return alert(result.response.data.message);
        
        alert('패스워드가 변경되었습니다.');
        history.push('/login');
        
```

2021-07-24 14:02 UTC, voidmatcha commented on src/pages/PasswordPage/PasswordPage.js
> +    } else if (mode === 'find') {
```suggestion
    } 
    if (mode === 'find') {
```

2021-07-24 14:02 UTC, voidmatcha commented on src/pages/PasswordPage/PasswordPage.js
> +export default function FindPassword({ history, location }) {
```suggestion
export default function FindPassword({ history, location: { pathanme, search } }) {
```

2021-07-24 14:02 UTC, dididy commented on src/pages/PasswordPage/PasswordPage.stories.js
> +export const login = () => <PasswordPage />;
https://github.com/witherview/witherview_frontend/pull/119/commits/152aa3d6ad1582497fba20d8e59032a259f171b3

 해결 하였습니다!

2021-07-26 13:21 UTC, dididy approved these changes
수고 많으셨습니다~!!

2021-07-29 03:54 UTC, merged