refactor: 💡 스터디룸 만들기 모달 UI를 업데이트한다
witherview/witherview_frontend pull request #121
Opened 2021-07-14 23:31 UTC by wooooooood

> resolve #120 

## Detail & Solution
- 스터디룸 만들기 모달 UI를 현재 제플린에 맞게 업데이트합니다

## What I did

## What I need to do

2021-07-24 13:13 UTC, dididy requested changes

2021-07-24 13:13 UTC, dididy commented on src/components/organisms/Modal/StudyMakeModal/StudyMakeModal.js
>          date,
{
  "category": "string",
  "date": "yyyy-MM-dd",
  "description": "string",
  "industry": "string",
  "job": "string",
  "time": "HH:mm:ss",
  "title": "string"
}
date와 time에서 이 형식을 지켜야 합니다!

2021-07-24 13:13 UTC, dididy commented on src/components/organisms/Modal/StudyMakeModal/StudyMakeModal.js
> +                  dateFormat="yyyy.MM.dd -eee"
```suggestion
                  dateFormat="yyyy.MM.dd - eee"
```

2021-08-16 08:50 UTC, wooooooood commented
Update. 카테고리 항목 빼고 api 잘 날라가는지 테스트해야함

2021-08-22 11:34 UTC, dididy approved these changes

2021-08-22 11:34 UTC, dididy commented on src/components/organisms/Modal/StudyMakeModal/StudyMakeModal.js
> +        time: `${time}:00`,
형식을 요렇게 줘야 했군요 수고 많으셨습니당

2021-08-22 23:10 UTC, merged