Jh
witherview/witherview_frontend pull request #65
Opened 2021-04-26 21:19 UTC by chjjh0

> resolve #57

## Detail & Solution
연습 내역 다시보기 카드뷰 컴포넌트를 구현합니다
 
## What I did
컴포넌트를 작성했지만, 퍼블리싱 측면(구조, 스타일링, 반응형, 웹표준 등)에서 미처리 됐거나 부족합니다.
리뷰를 통해 퍼블리싱 관련 의견 주시면 좀 더 다듬어 완성도 높게 수정하려 합니다.  

## What I need to do

2021-04-27 08:39 UTC, dididy reviewed
수고 많으셨습니다.

몇가지 생각해보아야 할 부분에 코멘트 남겨두었습니다.

2021-04-27 08:39 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +  const [title] = useState('12월 1일 혼자연습');
이부분은 추후에 props로 받아오게 될 부분인거 같은데 어떻게 생각하시나요?

2021-04-27 08:39 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +}
indent가 한단계 들어가야 할 것 같습니다.

2021-04-27 08:39 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +}
이부분도 마찬가지로 indent가 한단계 더 들어가면 좋을 것 같습니다.

2021-04-27 08:39 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.stories.js
> +};
스토리를 잘 만들어 두셨네요! args로 title, description, time를 주는걸 보면 역시 ReplayCardView에서 이부분을 props로 받아서 처리하시는걸 의도하신 것 같습니다. 이에 맞게 수정할 필요가 있을 것 같아요.

2021-04-27 08:39 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +  box-shadow: 0 0.6vh 1.2vh 0 rgba(4, 4, 161, 0.1);
통일성을 위해 기준을 vh로 변경해주시면 좋을 것 같습니다. 기준은 현재 px 단위에 10을 나눈 값을 주면 됩니다.

추후에 px이나 rem 단위로 리펙토링을 다시하게 될 듯 합니다.

```suggestion
  display: flex;
  flex-direction: column;
  border-radius: 1vh;
  width: 33.4vh;
  height: 36.8vh;
  box-shadow: 0 0.6vh 1.2vh 0 rgba(4, 4, 161, 0.1);
```

2021-04-27 08:40 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +  const [title] = useState('12월 1일 혼자연습');
https://github.com/witherview/witherview_frontend/pull/65#discussion_r620988936

2021-04-28 12:38 UTC, chjjh0 commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +  const [title] = useState('12월 1일 혼자연습');
일단 mocking용으로 작성됐습니다, 추후 말씀처럼 props로 수정할 예정입니다~

2021-04-28 12:39 UTC, chjjh0 commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +}
넵 tab관려 eslint 처리하다가 놓친것 같네요~ 수정하겠습니다!

2021-05-05 11:52 UTC, dididy requested changes
스토리북으로 구현된걸 확인하면서 놓치셨던 부분에 대해 코멘트 남겼습니다. 확인 부탁드립니다!

2021-05-05 11:52 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +          <A.Icon type="clock_black" alt="" />
type을 dots로 바꾸셔야 할 것 같습니다!
<img width="987" alt="Screen Shot 2021-05-05 at 8 44 37 PM" src="https://user-images.githubusercontent.com/16266103/117136012-bec92700-ade2-11eb-81a2-28e3d13bb605.png">

2021-05-05 11:52 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +          <A.Icon type="clock_black" alt="" />
해당 아이콘은 사용되지 않을 것 같습니다.

2021-05-05 11:52 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +          <p>{title}</p>
title에 bold가 적용되지 않았습니다.

2021-05-05 11:52 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +        <img src={tempImg} alt="temp" />
src에 아래 url을 넣으면 좀 더 확인하기 좋다고 생각됩니다.

https://user-images.githubusercontent.com/16266103/117136358-3b5c0580-ade3-11eb-8563-e751ceedd726.png

2021-05-05 11:52 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +        <p className="videoTime">{videoTime}</p>
이부분은 두 지점으로 나뉘어야 한다고 판단됩니다.

<img width="93" alt="Screen Shot 2021-05-05 at 8 49 53 PM" src="https://user-images.githubusercontent.com/16266103/117136523-72321b80-ade3-11eb-8440-777a55e20650.png">

숫자와 단위의 글꼴 스타일이 다르므로 이를 처리해주어야 합니다.

2021-05-05 11:52 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +        <A.Icon type="play_pupple" />
이 아이콘은 hover시 노출되게 될텐데 css의 :hover 속성으로 처리해주셔야 할 것 같습니다.

2021-07-26 13:56 UTC, Sung-jin commented on src/components/molecules/HoverDropDown/HoverDropDown.js
> +const WrapMenu = styled.div`
변수 하나에 nested ?? 형태의 스타일드 컴포넌트로 정의하는게 좋을 것 같습니다.

2021-07-26 13:56 UTC, Sung-jin commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +const Wrapper = styled.div`
여기는 전체를 합치는 것 보다, 작성하신 형태로 묶는 단위로 나눠서 중첩 형태의 스타일드 컴포넌트도 나쁘지 않을 것 같습니다. 👍

전체를 다 한번에 중첩 스타일드 컴포넌트를 하면 보기가 어려운데, 작성하신 방법은 보기가 훨씬 편한 것 같습니다.

다른분들 의견은 어떠신가요??

2021-07-26 13:56 UTC, Sung-jin commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +  const day = numberPad(`${createdAt.getDay()}`);
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay

getDay() 는 일 - 토 를 0 - 6 으로 리턴하는데, 현재 사용하는 부분은
`${month}월 ${day}일` 형태로 사용하고 있습니다.

의도하신 부분이 맞나요? 그리고 month 의 경우에도 0부터 시작됩니다.

2021-07-26 13:56 UTC, Sung-jin commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +            { id: 1, title: '삭제', func: () => {} },
수정/삭제 부분은 추후 구현 예정인가요?

2021-07-26 14:01 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +            { id: 1, title: '삭제', func: () => {} },
아직 API가 나오지 않았습니다..

2021-07-26 14:02 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +const Wrapper = styled.div`
네 길어지면 상황에 맞게 나누면 좋을 것 같아요!

2021-07-26 14:03 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +  const day = numberPad(`${createdAt.getDay()}`);
이부분 수정해야겠네요 짚어주셔서 감사합니다!

2021-07-26 14:04 UTC, dididy commented on src/components/molecules/HoverDropDown/HoverDropDown.js
> +const WrapMenu = styled.div`
네네 이부분은 그렇게 처리하도록 하겠습니다~

2021-07-26 14:47 UTC, dididy commented on src/components/molecules/HoverDropDown/HoverDropDown.js
> +const WrapMenu = styled.div`
@Sung-jin 반영하였습니다~ f1801af

2021-07-26 14:48 UTC, dididy commented on src/components/organisms/ReplayCardView/ReplayCardView.js
> +  const day = numberPad(`${createdAt.getDay()}`);
@Sung-jin 반영하였습니다! 72f1db2

2021-07-27 10:33 UTC, Sung-jin approved these changes
고생하셨습니다. 👍

2021-07-27 14:15 UTC, dididy approved these changes

2021-07-27 14:15 UTC, merged