refactor: 💡 sub-header 컴포넌트 작성
witherview/witherview_frontend pull request #72
Opened 2021-05-06 12:45 UTC by Sung-jin

공통 컴포넌트로 작성

✅ Closes: #70

> resolve #70 

## Detail & Solution
* 기획 화면 중, 설명 텍스트 + 컴포넌트 형태가 몇몇 존재합니다.
* 이러한 컴포넌트들의 설명 부분을 공통으로 관리하는 컴포넌트를 구현하였습니다.
* 사용방법
```jsx
<SubHeader
  fontSize={24}
  subHeaderText="서브헤더"
  subTitleColor="#6e6eff"
>
  <span>
    본문
  </span>
</SubHeader>
```

## What I did

![image](https://user-images.githubusercontent.com/28996915/117299503-952c0080-aeb3-11eb-8b8e-4d2140dabf6d.png)
![image](https://user-images.githubusercontent.com/28996915/117299751-da503280-aeb3-11eb-9040-43f6c0de681b.png)

* 위와 같이 **기업 이름/관심 산업_Main** 부분의 텍스트와 특정 컴포넌트가 같이 쓰이는 경우가 존재하여, 텍스트 부분을 공통 컴포넌트로 사용할 수 있도록 구현

## What I need to do

2021-05-06 12:49 UTC, Sung-jin commented on src/components/atoms/SubHeader/SubHeader.js
> +        &nbsp;
경험상, 같은 행에 어떤 컴포넌트는 서브 타이틀이 있고, 어떤 컴포넌트는 서브 타이틀이 없는 경우가 있는 경우가 종종 있었습니다.

예를들어, 서브 타이틀이 있는 텍스트 필드와 그냥 텍스트 필드만 존재하는 경우에 서브 타이틀이 없는 텍스트 필드가 있는 텍스트 필드의 높이를 맞추기 위해 css 를 추가하는 등의 추가 행위가 필요합니다.
이를 해결하기 위해 &nbsp; 를 추가해서 같은 행에 대해서는 서브 타이틀 부분의 크기는 동일하도록 만들었습니다.

2021-05-09 15:41 UTC, voidmatcha requested changes
간단하게 눈에 보이는 부분에 대해서 리뷰 남겨두었습니다.

수고 많으셨습니다!

2021-05-09 15:41 UTC, voidmatcha commented on src/components/atoms/SubHeader/SubHeader.js
> +  font-style: normal;
이부분은 의미없는 css 인 것 같습니다.
```suggestion

```

2021-05-09 15:41 UTC, voidmatcha commented on src/components/atoms/SubHeader/SubHeader.js
> +  text-align: left;
이부분도 꼭 필요한 이유가 있을까요?

2021-05-09 15:41 UTC, dididy commented on src/components/atoms/SubHeader/SubHeader.js
> +/* eslint-disable indent */
어떤 문제였는지 알 수 있을까요?

2021-05-09 15:41 UTC, voidmatcha commented on src/components/atoms/SubHeader/SubHeader.js
> +  children: PropTypes.element.isRequired,
isRequired를 사용하는 경우 defaultProps를 추가하면 좋을 것 같습니다.

2021-05-09 15:42 UTC, dididy commented on src/components/atoms/SubHeader/SubHeader.js
> +        &nbsp;
&nbsp;는 공백이라고 알고있는데 `같은 행에 대해서는 서브 타이틀 부분의 크기는 동일하도록 만들었습니다.` 이게 어떻게 가능한지 이해가 되지 않습니다.

2021-05-19 13:28 UTC, Sung-jin commented on src/components/atoms/SubHeader/SubHeader.js
> +  font-style: normal;
제거하겠습니다.

2021-05-19 13:28 UTC, Sung-jin commented on src/components/atoms/SubHeader/SubHeader.js
> +/* eslint-disable indent */
다른 컴포넌트 복사하면서 남아있었던 부분이네요. 제거하겠습니다.

2021-05-19 13:28 UTC, Sung-jin commented on src/components/atoms/SubHeader/SubHeader.js
> +  text-align: left;
서브 타이틀 부분 (컴포넌트 위에 있는 텍스트) 에 들어가는 스타일 입니다.
text-align/ㅣletter-space 는 필요없네요.
제거하겠습니다.

2021-05-19 13:28 UTC, Sung-jin commented on src/components/atoms/SubHeader/SubHeader.js
> +        &nbsp;
말로 전달했었던거 같은데, 다시 정리하겠습니다.

같은 영역을 가지는 행에 컴포넌트들 중 하나는 서브 타이틀을 가지고, 하나는 타이틀 없이 가지는 경우가 종종 있었습니다.
이때, 서브 타이틀이 존재하면 그 영역만큼 크기가 높아지게 됩니다.
하지만 이때 대부분 컴포넌트끼리 높이가 같게 표현되는 경우가 대부이어서 서브 타이틀 영역 부분을 계속 존재할 수 있도록 공백을 추가한 형태입니다.

![image](https://user-images.githubusercontent.com/28996915/118820056-e2b35f00-b8f0-11eb-8a75-8b7b303c9723.png)

이런 것처럼요.

2021-05-19 13:28 UTC, Sung-jin commented on src/components/atoms/SubHeader/SubHeader.js
> +  children: PropTypes.element.isRequired,
조금 애매한 부분이, 해당 컴포넌트는 서브 타이틀만 사용하기 위한 컴포넌트로 목적으로 구현된게 아닙니다.
어떠한 컴포넌트에 서브 타이틀이 있는 경우에 서브 타이틀 부분을 공통으로 사용하려고 만든 컴포넌트입니다.

```
children = <span>컴포넌트는 필수입니다.</span>
```

와 같은 기본 값을 넣는게 좋을까요?

2021-06-01 21:21 UTC, dididy commented on src/components/atoms/SubHeader/SubHeader.js
> +  children: PropTypes.element.isRequired,
@Sung-jin 기본값이 없어도 상관 없을 것 같습니다!

2021-06-01 21:21 UTC, dididy approved these changes
수고 많으셨어요. 승인합니다!

2021-06-13 05:36 UTC, merged