관심 산업/직무 태그 컴포넌트를 추가한다
witherview/witherview_frontend pull request #75
Opened 2021-05-09 10:42 UTC by wooooooood

> resolve #43 

## Detail & Solution
- 관심 산업/직무 태그 컴포넌트를 추가
## What I did
- storybook atom으로 +, X 아이콘을 추가한다.
- storybook molecule로 삭제 태그, 추가 태그를 추가한다.
## What I need to do
- [ ] CSS개선 / 코드리뷰 반영

질문이 있어서 리뷰 부탁드립니다~
아래 사진처럼 아이템 자체가 딱맞게 안잡히는 문제가 있어서 CSS를 조금 더 손봐야할것같은데 혹시 해결해보신 경험이 있으신지 또는 제가 잘못 작성한 부분이 있는지 리뷰 부탁드려요! 감사합니당
<img width="356" alt="Screen Shot 2021-05-09 at 6 07 43 PM" src="https://user-images.githubusercontent.com/40855076/117568940-1c6cb480-b0fe-11eb-83bc-07db8d36c9f7.png">
<img width="348" alt="Screen Shot 2021-05-09 at 7 39 28 PM" src="https://user-images.githubusercontent.com/40855076/117568984-4e7e1680-b0fe-11eb-96ab-2cf29c568f59.png">

2021-05-09 12:51 UTC, Sung-jin commented on src/components/atoms/CloseIcon/CloseIcon.js
> +  &:after {
```
.close {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  vertical-align: middle;
  font-size: 30px;
}
.close:after {
  display: flex;
  content: '\00d7';
  font-size: 20px;
}


<i class="close">
	123
</i>
```

![image](https://user-images.githubusercontent.com/28996915/117572862-d6b8e780-b10f-11eb-8470-3cf9d1d8e748.png)

이런식으로 한번 해보시겠어요?

사용하는 곳에서는 text 를 prop 으로 넘겨서 

```
<i>
    {text}
</i>
```

이런식으로 사용하면 텍스트가 앞에 붙고, 그 뒤에 아이콘이 붙는 형태로 갈 수 있게 사용할 수 있을 것 같습니다.

2021-05-09 12:51 UTC, Sung-jin commented on src/components/molecules/CloseTag/CloseTag.js
> +const Content = styled.p`
화학 이라는 텍스트가 잡히는 영역보다 올라가 보이는게, 아마 p 태그가 기본적으로 마진이 있어서 그런것 같습니다.

해당 스타일에 마진을 제거하거나, span 으로 한번 테스트 해보시겠어요?

2021-05-09 12:51 UTC, Sung-jin commented on src/components/atoms/PlusIcon/PlusIcon.js
> +    content: '\\00d7';
유니코드로 아이콘을 사용하는데, 아이콘 마다 컴포넌트를 작성하는게 아니라 사용하고 싶은 아이콘을 prop 으로 전달받아서 그걸 유니코드로 변환핵서 content 에 넣는 형태는 어떨가요?

예를들어서 

```
iconMapper = {
   close: '\\00d7',
   plus: '\002B'
...
}

content: ${({ iconText }) => iconMapper['iconText']);
```

요런 느낌으로요.

2021-05-09 15:18 UTC, dididy commented on src/components/atoms/PlusIcon/PlusIcon.js
> +    content: '\\00d7';
저도 이방법이 더 좋아 보입니다.

2021-05-09 15:34 UTC, dididy requested changes
변경해야 할 부분 코멘트 달아두었습니다.

개인적으로 태그는 하나의 컴포넌트에서 props에 따라 close tag나 add tag가 선택되게끔 하는 것이 좋지 않을까 하는데 어떻게 생각하시나요?

2021-05-09 15:34 UTC, dididy commented on src/components/atoms/CloseIcon/CloseIcon.js
> +    font-size: 17px;
vh 로 바꿔주세요

2021-05-09 15:34 UTC, dididy commented on src/components/atoms/PlusIcon/PlusIcon.js
> +    font-size: 17px;
vh로 바꿔주세요

2021-05-09 15:34 UTC, dididy commented on src/components/molecules/AddTag/AddTag.js
> +  border-radius: 20px;
vh로 바꿔주세요

2021-05-09 15:34 UTC, dididy commented on src/components/molecules/CloseTag/CloseTag.js
> +  border-radius: 20px;
vh로 바꿔주세요

2021-05-09 15:34 UTC, dididy commented on src/components/molecules/CloseTag/CloseTag.js
> +  border: solid 0.2vh ${({ backgroundColor }) => backgroundColor};
해당 라인을 제거해야 text가 어긋나는 부분을 해결할 수 있습니다.

우측 ICON이 가운데 정렬되게끔 할려면 추가적으로
```css
display: inline-flex;
align-items: center;
```
이렇게 두가지 속성을 추가해주시면 됩니다.

<img width="803" alt="Screen Shot 2021-05-10 at 12 30 49 AM" src="https://user-images.githubusercontent.com/16266103/117577940-f9a2c600-b126-11eb-89bb-910236c4d7d0.png">

2021-05-20 14:34 UTC, wooooooood commented on src/components/molecules/CloseTag/CloseTag.js
> +const Content = styled.p`
정훈님과 용재님이 폰트문제(폰트 자체가 하단에 여백이 있는것같네요ㅠㅠ)로 보여진다고 확인해주셔서 야매로 위에 임의 마진을 추가하기로 했습니다! 감사합니다~

2021-05-20 14:38 UTC, wooooooood commented on src/components/molecules/CloseTag/CloseTag.js
> +  border: solid 0.2vh ${({ backgroundColor }) => backgroundColor};
리뷰 감사합니다~!!

2021-05-23 11:29 UTC, wooooooood commented
<img width="322" alt="Screen Shot 2021-05-23 at 8 24 58 PM" src="https://user-images.githubusercontent.com/40855076/119258604-62993c00-bc05-11eb-84f0-470f93c2d51f.png">
<img width="317" alt="Screen Shot 2021-05-23 at 8 24 44 PM" src="https://user-images.githubusercontent.com/40855076/119258606-65942c80-bc05-11eb-810f-14693248149e.png">

isAddingTag를 기점으로 컴포넌트 변경

2021-05-28 15:05 UTC, dididy requested changes
요구사항을 잘 반영해주셨네요! 리뷰가 늦어서 죄송합니다. 

if로 jsx return 분기를 만드는 것 보다는 &&이나 삼항연산자로 줄이는게 더 나아보이는데 어떻게 생각하시나요?

아래에 제가 생각하는 코드 형태를 코멘트로 남겨두었습니다.

2021-05-28 15:05 UTC, dididy commented on src/components/molecules/Tag/Tag.js
> +  );
```suggestion
  return (
    <Wrapper onClick={func} tagColor={tagColor} isAddingTag={isAddingTag}>
      {isAddingTag && <PlusIcon color={contentColor} />}
      <Content contentColor={contentColor} isAddingTag={isAddingTag}>
        {!isAddingTag ? '추가' : closeTagText}
      </Content>
      {!isAddingTag && <CloseIcon color={contentColor} />}
    </Wrapper>
  );
```
이렇게 축약할 수 있을 것 같습니다!

2021-05-29 07:54 UTC, wooooooood commented on src/components/molecules/Tag/Tag.js
> +  );
확인했습니다! 리뷰 감사드립니다🎉

2021-05-30 00:24 UTC, dididy requested changes
자잘한 개선점을 찾아보았습니다!

2021-05-30 00:24 UTC, dididy commented on src/components/molecules/Tag/Tag.js
> +import theme from '../../../style/theme';
```suggestion
import TagIcon from '@atoms/TagIcon';
import theme from '@style/theme';
```

요렇게 바꾸면 좋지 않을까요?

2021-05-30 00:24 UTC, dididy commented on src/components/molecules/Tag/Tag.js
> +    isAddingTag ? `solid 0.2vh ${tagColor}` : ''};
```suggestion
  ${({ isAddingTag, tagColor }) =>
    isAddingTag && `border: solid 0.2vh ${tagColor}`};
```

삼항연산자를 굳이 쓸 필요가 없을 것 같습니다!

2021-05-30 05:03 UTC, wooooooood commented on src/components/molecules/Tag/Tag.js
> +    isAddingTag ? `solid 0.2vh ${tagColor}` : ''};
아하 저 항상 삼항 대체?로 && 사용하는게 헷갈렸는데 짚어주셔서 감사드려요!!👍👍

2021-05-30 06:45 UTC, dididy approved these changes
승인합니다!

2021-05-30 06:45 UTC, dididy commented on .storybook/webpack.config.js
> +    '@routes': path.resolve(__dirname, '../src/routes'),
아 요부분이 기존에 처리가 안되어있었군요..

2021-05-30 06:49 UTC, merged