Input에 대한 Validation 을 추가한다
witherview/witherview_frontend pull request #81
Opened 2021-05-25 13:09 UTC by Sung-jin

> resolve #53 

## Detail & Solution
* 기존 input 컴포넌트에 validation 기능 및 error message 기능을 추가한다.

## What I did
* validation 체크는 `(v) => {return boolean} || 'errorMessage'` 형태로 전달받으며, 앞의 함수 결과에 따라 메세지가 출력되는 형태로 구현했습니다.

```jsx
example

export const inputBar = (args) => {
  const [value, setValue] = useState('');
  const [isValid, setIsValid] = useState(false);
  const rules = [(v) => !!(v) || '에러메시지', (v) => v > 10 || '최소값보다 작습니다.'];

  useEffect(() => {
    if (isValid) console.log(`유효성 값 변경 : ${isValid}`);
  }, [isValid]);
  return (
    <InputBar
      {...args}
      value={value}
      onChange={(e) => setValue(e.target.value)}
      isValid={setIsValid}
      rules={rules}
    />
  );
};
```
* 위와 같이 value 의 값을 rules 의 모든 rule 과 대입하여, validation 에 걸리는 부분의 message 를 출력하는 형태입니다.

![image](https://user-images.githubusercontent.com/28996915/119502425-e178ab00-bda4-11eb-8579-505420161f3f.png)

## What I need to do?
* 의문문으로 변경해서, 해당 기능을 작성하면서 고민한 부분을 공유하겠습니다.
1. validation 에 통과하지 못하여 message 가 표시되는 ui 는 제플린에 없어서, 우선 이미지와 같이 구현했습니다. 색상이랑 글씨크기 등 괜찮나요?
2. 해당 컴포넌트에서는 validation 통과 여부를 isValid: Function (return boolean) 형태로 했으며, 사용하는 곳에서 각 컴포넌트의 validation 을 확인하여 처리하도록 의도했습니다. 괜찮을까요?
3. 코드에 댓글을 추가하였듯, error message 를 추가하기 위해 전체 container 태그를 추가했습니다. 그로인해 기존에 input 을 사용하던 곳에 영향이 있어서 우선 기존처럼 보이게 변경했습니다. 그런데, 아래와 같이 error message 는 따로 css 가 없어서 사용하는 곳 마다 크기가 이상해 보이는 현상이 있네요. 이는 어떻게 해결하는게 좋을까요?
4. 
![image](https://user-images.githubusercontent.com/28996915/119503416-e9851a80-bda5-11eb-9432-e3728b8e3860.png)

2021-05-25 13:13 UTC, Sung-jin commented on src/components/organisms/Modal/QuestionListSaveModal/QuestionListSaveModal.js
>  `;
리뷰 요청의 문의사항 부분입니다.

기존 input 에 container 를 하나 추가하다 보니, 기존 css 에 div 추가해야 기존 디자인이 적용됩니다. 괜찮을까요?
그리고 error message 도 theme.input 에 정의하는게 좋을까요?

2021-05-28 04:03 UTC, dididy commented on src/components/organisms/Modal/QuestionListSaveModal/QuestionListSaveModal.js
>  `;
오늘 풀받아서 확인해보겠습니다!

2021-05-29 13:59 UTC, dididy requested changes
피드백 남겨두었습니다!

2021-05-29 13:59 UTC, dididy commented on .gitignore
> +yarn.lock
yarn.lock은 .gitignore에 추가할 필요가 없을 것 같습니다!
```suggestion
```

2021-05-29 13:59 UTC, dididy commented on src/components/atoms/InputBar/InputBar.stories.js
> +};
```suggestion
  useEffect(() => {
    if (isValid) console.log(`유효성 값 변경 : ${isValid}`);
  }, [isValid]);
  return (
    <InputBar
      rules: [
        (v) => !!(v) || '해당 데이터는 필수입니다.',
      ]
      value={value}
      onChange={(e) => setValue(e.target.value)}
      isValid={setIsValid}
    />
  );
};
```
이런식으로 수정하면 어떨가요?

2021-07-27 14:43 UTC, dididy requested changes
성진님 커밋 메시지가 비어있는 부분들을 정리해주시면 좋을 것 같습니다!

2021-08-15 04:54 UTC, merged