Icon 컴포넌트 유지보수성 강화를 위해 리팩토링한다
witherview/witherview_frontend pull request #89
Opened 2021-06-07 08:25 UTC by chjjh0

> resolve #88

## Detail & Solution
if문과 삼항으로 작성 된 분기 로직을 변경한다

## What I did
분기 로직을 객체 리터럴 및 스위치문으로 변경

## What I need to do

2021-06-08 14:40 UTC, dididy requested changes
3항연산자 중첩으로 가독성이 떨어졌던 부분을 리팩토링 해주셔서 감사합니다. 제 생각에는 현재 PR에 8d4153bc606d0ca0fd23aac5c9f5cb589596096b 이 커밋만 있으면 될 것 같습니다.

간단한 코멘트를 남겨놨는데 반영해주시면 감사하겠습니다.

수고 많으셨습니다!

2021-06-08 14:40 UTC, dididy commented on src/components/atoms/Icon/Icon.js
> +};
해당 함수는 snippet에 정의하여 import 해주시면 좋을 것 같습니다.

2021-06-08 14:40 UTC, dididy commented on src/components/atoms/Icon/Icon.js
> +const borderRadiusSize = { ...basicSize };
확인해본 결과 basicSize와 동일한 값을 담는 변수인 것 같은데 명시적인 부분을 위해서 새로 정의한 것 일까요?

2021-06-08 14:40 UTC, dididy commented on src/components/atoms/Icon/Icon.js
> +      // case 'check_on':
불필요한 주석은 지우는게 좋을 것 같습니다.

2021-06-08 20:39 UTC, chjjh0 commented on src/components/atoms/Icon/Icon.js
> +const borderRadiusSize = { ...basicSize };
넵 그냥 cosnt borderRadiusSize = basicSize로 할당 할 수도 있지만, 32번 다음 라인에서 작성된 widthSize, heightSize에서는 덮어쓰기 를 위해 전개연산자를 활용하는 패턴과 일관성을 위해서 전개연산자를 활용하여 작성했습니다

2021-06-08 20:42 UTC, chjjh0 commented on src/components/atoms/Icon/Icon.js
> +};
적용했습니다~

2021-06-08 20:43 UTC, chjjh0 commented on src/components/atoms/Icon/Icon.js
> +      // case 'check_on':
적용했습니다~

2021-06-08 23:23 UTC, voidmatcha commented on src/components/atoms/Icon/Icon.js
> +const borderRadiusSize = { ...basicSize };
같은 값을 가지는 변수가 두개라 하나로 줄여도 좋을 것 같은데 어떻게 생각하시나요? 혹시 추후 확장성을 위해 새로 만드신 걸까요?

2021-06-10 10:02 UTC, wooooooood approved these changes
수고하셨습니다! 👍

2021-06-10 13:41 UTC, dididy approved these changes
수고 많으셨습니다!

2021-06-12 12:46 UTC, merged